<?php
/**
 * Render slideshow component for Hyvä theme
 */
$titleType = $this->getData('mageos_slideshow_title_type');
?>

<?php if (!empty($this->getData('mageos_slideshow_title'))): ?>
<<?= $titleType ?>><?= $this->getData('mageos_slideshow_title'); ?></<?= $this->getData('mageos_slideshow_title_type'); ?>>
<?php endif; ?>

<?php if (!empty($this->getData('mageos_slideshow_description'))): ?>
<div><?= $this->getData('mageos_slideshow_description'); ?></div>
<?php endif; ?>

<?= $this->renderMainTemplate(); ?>
