<?php
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\Widgetkit\Block\Widgets\HyvaWidget;
use Magento\Framework\Escaper;

/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var HyvaWidget $block
 * @var Escaper $escaper
 */

$widgetCssClass = $block->getData('cssClass');
$uniqId = $block->getData('uid');
?>
<?php
$scriptString = '
    const { create } = window.twind;
    const { virtualSheet } = window.TwindSheets;
    const sheet = virtualSheet();
    const { tw } = create({ sheet });

    const targetSelector = \'widget' . $uniqId . '\';
    const target = document.querySelector(\'#\' + targetSelector);
    const tailwindClasses = [];

    function collectTailwindClasses(element) {
        if (element.classList && element.classList.length > 0) {
            const classes = Array.from(element.classList).join(\' \');
            tailwindClasses.push(classes);
        }

        element.childNodes.forEach(child => {
            if (child.nodeType === 1) collectTailwindClasses(child);
        });
    }

    collectTailwindClasses(target);
    tailwindClasses.forEach(cls => tw(cls));

    const style = document.createElement(\'style\');
    style.id = targetSelector + \'-style\';
    if (document.getElementById(style.id)) {
        document.getElementById(style.id).remove();
    }

    const prefix = \'.pagebuilder-stage-wrapper .' . $widgetCssClass . '\';
    style.textContent = sheet.target.map(rule => {
        const match = rule.match(/^([^{}]+)\{([\s\S]+)\}$/);
        if (!match) return rule;

        const selectors = match[1]
            .split(\',\')
            .map(s => `${prefix} ${s.trim()}`)
            .join(\', \');

        return `${selectors}{${match[2]}}`;
    }).join(\'\n\');
    document.head.appendChild(style);
';
echo /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'module'], $scriptString, false);
?>
