<?php

use MageOS\Widgetkit\Block\Widgets\Slideshow;

/**
 * @var Slideshow $this
 */

$params = $this->getData('params');
$item = $this->getData('item');

// Title
$title = [
    'type' => $item['title_tag'],
    'class' => $this->resolveExpression([
        'el-title',
        '',
    ], $params)
];

// Content
$content = [
    'class' => $this->resolveExpression([
        ''
    ], $params)
];

// Link
$linkContainer = [
    'class' => $this->resolveExpression([
        '',
    ], $params)
];

$container = [
    'class' => $this->resolveExpression([
        'w-xs max-w-full {@mageos_slideshow_overlay_width: small}',
        'w-sm max-w-full {@mageos_slideshow_overlay_width: medium}',
        'w-md max-w-full {@mageos_slideshow_overlay_width: large}',
        'inset-x-0 {@mageos_slideshow_overlay_width: expand}',
        'top-0 left-0 {@mageos_slideshow_overlay_position: top-left}',
        'top-0 right-0 {@mageos_slideshow_overlay_position: top-right}',
        'bottom-0 left-0 {@mageos_slideshow_overlay_position: bottom-left}',
        'bottom-0 right-0 {@mageos_slideshow_overlay_position: bottom-right}',
        'text-left {@mageos_slideshow_overlay_text_alignment: left}',
        'text-center {@mageos_slideshow_overlay_text_alignment: center}',
        'text-right {@mageos_slideshow_overlay_text_alignment: right}',
    ], $params)
];


$link = [
    'type' => 'a',
    'href' => $item['button_link'],
    'class' => $this->resolveExpression([
        'btn btn-primary {@mageos_slideshow_overlay_link_type: button-primary}',
        'btn btn-secondary {@mageos_slideshow_overlay_link_type: button-secondary}',
        'cursor-pointer {@mageos_slideshow_overlay_link_type: link}',
    ], $params),
    'aria-label' => $item['button'],
    'target' => $this->resolveExpression([
        '_blank {@button_link_target}'
    ], $item)
];

if ($link && $item['button_link']) {

    $linkContainer['class'] .= ' ' . $this->resolveExpression([], $params);

    $item['title'] = $this->stripTags($item['title']);
    $item['content'] = $this->stripTags($item['content']);
}

?>
<?php if (!empty($item['title']) || !empty($item['content'])): ?>
<div class="slide-content card absolute my-4 mx-4 <?= $container['class']; ?>">
    <?php if (!empty($item['title'])) : ?>
    <<?= $title['type']; ?> class="<?= $title['class']; ?>"><?= $item['title'] ?></<?= $title['type']; ?>>
    <?php endif ?>

    <?php if (!empty($item['content'])) : ?>
    <div class="<?= $content['class']; ?>"><?= $item['content']; ?></div>
    <?php endif ?>

    <?php if ($item['button_link'] && $item['button']) : ?>
    <div class="<?= $linkContainer['class']; ?>">
        <<?= $link['type']; ?>
            class="<?= $link['class']; ?>"
            <?php if ($link['type'] === 'a'): ?>
            href="<?= $link['href']; ?>"
            aria-label="<?= $link['aria-label']; ?>"
            target="<?= $this->resolveExpression(['_blank {@link_target}'], $item); ?>"
            <?php endif; ?>>
            <?=  $item['button'] ?>
        </<?= $link['type']; ?>>
    </div>
    <?php endif ?>
</div>
<?php endif; ?>
