<?php

use MageOS\Widgetkit\Block\Widgets\Slideshow;

/**
 * @var Slideshow $this
 */

$params = $this->getData('params');

$navigation = [
    'class' => $this->resolveExpression([
        'flex {@mageos_slideshow_slidenav_visibility: show}',
        'hidden {@mageos_slideshow_slidenav_visibility: hide}',
        'absolute top-0 left-0 mx-4 my-4 {@mageos_slideshow_slidenav_position: top-left}',
        'absolute top-0 right-0 mx-4 my-4 {@mageos_slideshow_slidenav_position: top-right}',
        'absolute bottom-0 left-0 justify-left mx-4 my-4 {@mageos_slideshow_slidenav_position: bottom-left}',
        'absolute bottom-0 right-0 justify-rightl mx-4 my-4 {@mageos_slideshow_slidenav_position: bottom-right}',
        'relative my-4 flex-row {@mageos_slideshow_slidenav_position: above-left}',
        'relative my-4 justify-right { @mageos_slideshow_slidenav_position: above-right}',
        'relative my-4 flex-row {@mageos_slideshow_slidenav_position: below-left}',
        'relative my-4 justify-right {@mageos_slideshow_slidenav_position: below-right}',
        'absolute inset-0 justify-between {@mageos_slideshow_slidenav_position: default}',
    ], $params)
];
?>

<div class="<?= $navigation['class']; ?> items-center px-4 ">
    <button @click="prev('button')" class="btn btn-secondary p-2 z-10"
            <?php if (!$this->getData('params')['mageos_slideshow_loop']): ?>
            x-bind:disabled="currentIndex === 0"
            <?php endif; ?>
            aria-label="<?= __('Previous Slide'); ?>" data-prev="">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" class="rtl:-rotate-180" aria-hidden="true">
            <path d="m12 19-7-7 7-7M19 12H5"></path>
        </svg>
    </button>
    <button @click="next('button')" class="btn btn-secondary p-2 z-10"
            <?php if (!$this->getData('params')['mageos_slideshow_loop']): ?>
            x-bind:disabled="currentIndex + 1 === images.length"
            <?php endif; ?>
            aria-label="<?= __('Next Slide'); ?>" data-next="">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" class="rtl:-rotate-180" aria-hidden="true">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
    </button>
</div>
