<?php

use MageOS\Widgetkit\Block\Widgets\Slideshow;

/**
 * @var Slideshow $this
 */

$itemCount = 0;
$itemSettings = $this->getData('settings');
?>
<<?= $itemSettings['type']; ?>
    <?php if (isset($itemSettings['style'])): ?>
    style="<?= $itemSettings['style']?>"
    <?php endif; ?>
    class="<?= $itemSettings['class']; ?>"
    role="region"
    aria-roledescription="carousel"
    aria-label="Image Slider"
    data-track
>
<?php
foreach ($this->getData('items') as $item):
?>
    <?php $item['count'] = $itemCount; ?>
    <div class="slide-container absolute start-0 top-0 h-full w-full object-cover"
         x-data="{ index: <?= (int)$item['count'] ?> }"
         x-bind:class="{
            'transition duration-300 ease-in-out will-change-auto': transition,
            'z-1': currentIndex === index,
            'hidden': !transition && currentIndex !== index,
            'opacity-100': (transition === 'fade' || transition === 'blur-sm')  && currentIndex === index,
            'opacity-0 invisible': transition === 'fade' && currentIndex !== index,
            'translate-x-0': transition === 'slide' && currentIndex === index,
            '-translate-x-full': transition === 'slide' && currentIndex > index,
            'translate-x-full': transition === 'slide' && currentIndex < index
        }">
    <?= $this->renderItemMedia($item); ?>
    <?= $this->renderItemContent($item); ?>
    </div>
<?php $itemCount++;  endforeach; ?>
</div>
