<?php

use MageOS\Widgetkit\Block\Widgets\Slideshow;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;

/**
 * @var Slideshow $this
 * @var HyvaCsp $hyvaCsp
 * @var Escaper $escaper
 */

$params = $this->getData('params');
$uniqId = uniqid();

// slideshow container
$container = [
    'class' => $this->resolveExpression([
        'relative',
        'w-full max-w-3xl',
        'mx-auto overflow-hidden rounded-lg shadow-lg'
    ], $params)
];

// Items
$itemsSettings = [
    'type' => 'div',
    'class' => $this->resolveExpression([
        'snap-track',
        'h-auto {@mageos_slideshow_height: auto}',
        'h-screen {@mageos_slideshow_height: viewport}'
    ], $params),
    'style' => $this->resolveExpression([
        'min-height: {0}; {@mageos_slideshow_height: viewport}' => '100vh',
        'min-height: {0}; {@mageos_slideshow_height: auto}' => $params['mageos_slideshow_min_height'] . 'px',
        'max-height: {0}; {@mageos_slideshow_max_height}' => isset($params['mageos_slideshow_max_height']) ? $params['mageos_slideshow_max_height'] . 'px' : '',
        'aspect-ratio: {0}; {@mageos_slideshow_ratio}' => $params['mageos_slideshow_ratio']
    ], $params)
];

$slideshowContainerSettings = [
    'class' => $this->resolveExpression([
        'relative {@mageos_slideshow_navigation_position: top-left}',
        'relative {@mageos_slideshow_navigation_position: top-right}',
        'relative {@mageos_slideshow_navigation_position: top-center}',
        'relative {@mageos_slideshow_navigation_position: center-left}',
        'relative {@mageos_slideshow_navigation_position: center-right}',
        'relative {@mageos_slideshow_navigation_position: bottom-left}',
        'relative {@mageos_slideshow_navigation_position: bottom-right}',
        'relative {@mageos_slideshow_navigation_position: bottom-center}'
    ], $params),
];
?>

<div
    x-data="initSlideshow<?= $uniqId; ?>"
    class="mx-auto w-full <?= $slideshowContainerSettings['class']; ?>"
    x-on:keyup.right="next('button')"
    x-on:keyup.left="prev('button')"
>
    <?php if(
        in_array(
            $params['mageos_slideshow_slidenav_position'],
            ['above-left', 'above-right']
        )
    ): ?>
        <?= $this->renderSlideNavTemplate(); ?>
    <?php endif; ?>
    <div
        class="relative overflow-hidden"
        tabindex="0"
    >
        <?= $this->renderItems($itemsSettings); ?>

        <?php if(
            !in_array(
                $params['mageos_slideshow_slidenav_position'],
                ['above-left', 'above-right', 'below-left', 'below-right']
            )
        ): ?>
        <?= $this->renderSlideNavTemplate(); ?>
        <?php endif; ?>
    </div>
    <?php if(
        in_array(
            $params['mageos_slideshow_slidenav_position'],
            ['below-left', 'below-right']
        )
    ): ?>
        <?= $this->renderSlideNavTemplate(); ?>
    <?php endif; ?>
    <?= $this->renderNavTemplate(); ?>
</div>

<script>
    function initSlideshow<?= $uniqId; ?>() {
        return {
            images: [
                <?php foreach ($this->getData('items') as $index => $item): ?>
                '<?= isset($item['image']) ? $escaper->escapeUrl($item['image']) : ''; ?>',
                <?php endforeach; ?>
            ],
            arrowsNavigation: true,
            dotsNavigation: true,
            transition: '<?= $params['mageos_slideshow_transition']; ?>',
            loop: <?= (int)$params['mageos_slideshow_loop'] ? 'true' : 'false'; ?>,
            autoplay: <?= (int)$params['mageos_slideshow_autoplay'] ? 'true' : 'false'; ?>,
            autoplayDuration: <?= isset($params['mageos_slideshow_speed']) ? $params['mageos_slideshow_speed'] * 1000: 0; ?>,
            currentIndex: 0,
            autoplayInterval: null,
            autoplayProgress: 0,
            direction: 'next',
            init() {
                this.startAutoplayInterval('all');
            },
            set(index, from) {
                if (index > -1 && index < this.images.length) {
                    if (index > this.currentIndex) {
                        this.currentIndex = index;
                        if (!this.loop && this.currentIndex === this.images.length - 1) {
                            this.resetAutoplayInterval('all');
                        } else {
                            if (from === 'button') {
                                this.resetAutoplayInterval('all', true);
                            } else {
                                this.resetAutoplayInterval('timer', true);
                            }
                        }
                    } else if (index < this.currentIndex) {
                        this.currentIndex = index;
                        if (from === 'button') {
                            this.resetAutoplayInterval('all', true);
                        } else {
                            this.resetAutoplayInterval('timer', true);
                        }
                    }
                }
            },
            next(from) {
                this.direction = 'next';
                if (!this.loop && this.currentIndex === this.images.length - 1) {
                    return;
                }
                this.set((this.currentIndex + 1) % this.images.length, from);
            },
            prev(from) {
                this.direction = 'prev';
                if (!this.loop && this.currentIndex === 0) {
                    return;
                }
                this.set((this.currentIndex - 1 + this.images.length) % this.images.length, from);
            },
            startAutoplayInterval(mode) {
                if (this.autoplay && (mode === 'all' || mode === 'interval')) {
                    this.autoplayInterval = setInterval(() => this.next(), this.autoplayDuration);
                }
            },
            resetAutoplayInterval(mode, restart) {
                if (this.autoplay && (mode === 'all' || mode === 'interval')) {
                    clearInterval(this.autoplayInterval);
                    if (restart && mode === 'interval') {
                        this.startAutoplayInterval('interval');
                    }
                }
                if (restart && mode === 'all') {
                    this.startAutoplayInterval('all');
                }
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initSlideshow<?= $uniqId; ?>', initSlideshow<?= $uniqId; ?>), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
